title: 'Snipeeey'
description: "Snipeeey's Personal Website"
baseurl: ""
url: "https://snipeeey.com"

header_pages:
  - index.md
  - peter.md
  - about.md
  - contact.md

style: hacker

footer: 'Join My <a href="https://discord.gg/XBTzf4S">Discord</a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
